tls:
  certificates:
    - certFile: /mycert/wildcard.hs.lan/hs-end-entity-ecdsa.pem.crt
      keyFile:  /mycert/wildcard.hs.lan/hs-end-entity-ecdsa.pem.key
    - certFile: /mycert/dns.lan/hs-end-entity-ecdsa.pem.crt
      keyFile:  /mycert/dns.lan/hs-end-entity-ecdsa.pem.key
    - certFile: /mycert/ont.lan/hs-end-entity-ecdsa.pem.crt
      keyFile:  /mycert/ont.lan/hs-end-entity-ecdsa.pem.key

http:
  serversTransports:
    skip-tls:
      insecureSkipVerify: true

  # system or external services
  routers:
    ont:
      rule: "Host(`ont.lan`)"
      service: ont
      entryPoints:
        - websecure
      tls: {}
      serversTransports: skip-tls

    filebrowser:
      rule: "Host(`file.hs.lan`)"
      service: filebrowser
      entryPoints:
        - websecure
      tls: {}

    cockpit:
      rule: "Host(`cockpit.hs.lan`)"
      service: cockpit
      entryPoints:
        - websecure
      tls: {}
      serversTransports: skip-tls

    # containerized services
    forgejo:
      rule: "Host(`forgejo.hs.lan`)"
      service: forgejo
      entryPoints:
        - websecure
      tls: {}
      priority: 1

    share:
      rule: "Host(`share.hs.lan`)"
      service: share
      entryPoints:
        - websecure
      tls: {}
      priority: 1

    ha:
      rule: "Host(`ha.hs.lan`)"
      service: ha
      entryPoints:
        - websecure
      tls: {}
      priority: 1

    dns:
      rule: "Host(`dns.lan`)"
      service: dns
      entryPoints:
        - websecure
      tls: {}
      priority: 1

  services:
    ont:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1/"

    filebrowser:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:9000/"

    cockpit:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:9090/"

    forgejo:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3000/"

    share:
      loadBalancer:
        servers:
          - url: "http://psitransfer-private:3000/"

    ha:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:8123/"

    dns:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:8686/"