http:
  routers:
    filebrowser-public:
      rule: "Host(`file-hs.nduc.io.vn`)"
      service: filebrowser
      entryPoints:
        - web

    cockpit-public:
      rule: "Host(`cockpit-hs.nduc.io.vn`)"
      service: cockpit
      entryPoints:
        - web

    forgejo-public:
      rule: "Host(`forgejo-hs.nduc.io.vn`)"
      service: forgejo
      entryPoints:
        - web
      priority: 1

    share-public:
      rule: "Host(`share-hs.nduc.io.vn`)"
      service: share
      entryPoints:
        - web
      priority: 1

    ha-public:
      rule: "Host(`ha-hs.nduc.io.vn`)"
      service: ha
      entryPoints:
        - web
      priority: 1

    dns-public:
      rule: "Host(`dns-hs.nduc.io.vn`)"
      service: dns
      entryPoints:
        - web
      priority: 1

    notfound:
      rule: "Host(`nduc.io.vn`)"
      service: notfound
      entryPoints:
        - web

  services:
    notfound:
      loadBalancer:
        servers:
          - url: "http://host.container.internal:6060/"