# see `man dnf.conf` for defaults and possible options

[main]
fastestmirror=True
country=VN
max_parallel_downloads=10
keepcache=False
deltarpm=True
metadata_expire=6h
installonly_limit=3
skip_if_unavailable=True
