FROM alpine:latest AS builder

RUN apk add --no-cache \
    build-base \
    openssl-dev \
    openssl-libs-static \
    expat-dev \
    hiredis-dev \
    expat-static \
    zlib-static \
    bison \
    flex \
    wget \
    ca-certificates \
    tar

WORKDIR /src

RUN wget https://nlnetlabs.nl/downloads/unbound/unbound-latest.tar.gz \
    && tar xzf unbound-latest.tar.gz --strip-components=1

RUN ./configure \
    --enable-cachedb \
    --with-libhiredis \
    --enable-static \
    --disable-shared \
    --with-pthreads \
    --with-ssl=/usr \
    --with-libexpat=/usr \
    --disable-flto \
    LDFLAGS="-static -no-pie" \
    CFLAGS="-O2 -march=x86-64-v2 -mtune=ivybridge -pipe"

RUN make LDFLAGS="-static -all-static -no-pie" \
         LIBS="-lhiredis -lssl -lcrypto -lexpat -lz -lpthread" \
         -j$(nproc)

# Verify that the unbound binary is statically linked
RUN ldd unbound 2>&1 | grep -q "Not a valid dynamic program" \
    || { echo "ERROR: ldd check error or unbound binary is not statically linked after build!"; exit 1; }

RUN ldd unbound-checkconf 2>&1 | grep -q "Not a valid dynamic program" \
    || { echo "ERROR: ldd check error or unbound-checkconf binary is not statically linked after build!"; exit 1; }

# Verify that the unbound binary has cachedb module
RUN ./unbound -V | grep -q "cachedb" \
    || { echo "ERROR: cachedb module not found in unbound binary!"; exit 1; }


RUN make install \
    && strip /usr/local/sbin/unbound \
    && strip /usr/local/sbin/unbound-checkconf

FROM gcr.io/distroless/static-debian13

COPY --from=builder /usr/local/sbin/unbound /unbound
COPY --from=builder /usr/local/sbin/unbound-checkconf /unbound-checkconf

COPY unbound.conf /etc/unbound/unbound.conf

EXPOSE 53/udp
EXPOSE 53/tcp
EXPOSE 443/tcp
EXPOSE 853/tcp

ENTRYPOINT ["/unbound"]

CMD ["-d", "-c", "/etc/unbound/unbound.conf"]