server:
    interface: 0.0.0.0
    access-control: 198.18.0.0/16 allow
    username: ""
    chroot: ""
    do-daemonize: no
    logfile: ""
    pidfile: ""
    so-sndbuf: 0
    so-rcvbuf: 0
    directory: "/"
    prefetch: yes
    module-config: "respip cachedb iterator"
    log-servfail: yes

cachedb:
    backend: "redis"
    redis-server-host: "host.containers.internal"
    cachedb-check-when-serve-expired: no