server:
    interface: 0.0.0.0
    access-control: 198.18.0.0/16 allow
    username: ""
    chroot: ""
    do-daemonize: no
    logfile: ""
    pidfile: ""
    so-sndbuf: 0
    so-rcvbuf: 0
    directory: "/"
    prefetch: yes
    module-config: "dns64 cachedb respip validator iterator"
    serve-expired-ttl: 86400
    serve-expired-client-timeout: 0

cachedb:
    backend: "redis"
    redis-server-host: "host.containers.internal"
#    redis-server-password: "$REDIS_PASSWORD"
    cachedb-check-when-serve-expired: no